baseURL: "https://talk.zsxcoder.top"
languageCode: "zh-Hans"
title: "ZSX Moments"
theme: "moments"

pagination:
    pagerSize: 10
    path: "."

params:
    title: "ZSX Moments"
    signature: "每一段旅行，都有终点~"
    name: "钟神秀"
    quote:
      text: '这是基于Hugo的<a href="https://github.com/zsxcoder/notion-hugo-moments.git" target="_blank" rel="noopener noreferrer">Moment</a>说说，然后数据来自<strong>Notion</strong>。'
      author: "钟神秀"
    experimental:
      comment: true
